################################################################################
# Automatically-generated file. Do not edit!
################################################################################

C55_SRCS := 
A_SRCS := 
ASM_UPPER_SRCS := 
PINMUX_SRCS := 
EXE_SRCS := 
LDS_UPPER_SRCS := 
CPP_SRCS := 
CMD_SRCS := 
O_SRCS := 
ELF_SRCS := 
C??_SRCS := 
C64_SRCS := 
C67_SRCS := 
SA_SRCS := 
S64_SRCS := 
OPT_SRCS := 
CXX_SRCS := 
S67_SRCS := 
S??_SRCS := 
PDE_SRCS := 
SV7A_SRCS := 
SYSCFG_SRCS := 
K_SRCS := 
CLA_SRCS := 
S55_SRCS := 
LD_UPPER_SRCS := 
OUT_SRCS := 
INO_SRCS := 
LIB_SRCS := 
ASM_SRCS := 
S_UPPER_SRCS := 
SYSCONFIG_SRCS := 
S43_SRCS := 
LD_SRCS := 
CMD_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
C43_SRCS := 
OBJ_SRCS := 
LDS_SRCS := 
S_SRCS := 
CC_SRCS := 
S62_SRCS := 
C62_SRCS := 
C_SRCS := 
C55_DEPS := 
C_UPPER_DEPS := 
S67_DEPS := 
S62_DEPS := 
S_DEPS := 
OPT_DEPS := 
C??_DEPS := 
ASM_UPPER_DEPS := 
S??_DEPS := 
C64_DEPS := 
CXX_DEPS := 
S64_DEPS := 
INO_DEPS := 
GEN_CMDS := 
GEN_FILES := 
CLA_DEPS := 
S55_DEPS := 
SV7A_DEPS := 
EXE_OUTPUTS := 
C62_DEPS := 
C67_DEPS := 
PDE_DEPS := 
GEN_MISC_DIRS := 
K_DEPS := 
C_DEPS := 
CC_DEPS := 
BIN_OUTPUTS := 
GEN_OPTS := 
C++_DEPS := 
C43_DEPS := 
S43_DEPS := 
OBJS := 
ASM_DEPS := 
GEN_MISC_FILES := 
S_UPPER_DEPS := 
CPP_DEPS := 
SA_DEPS := 
C++_DEPS__QUOTED := 
OPT_DEPS__QUOTED := 
S_UPPER_DEPS__QUOTED := 
SA_DEPS__QUOTED := 
C??_DEPS__QUOTED := 
S67_DEPS__QUOTED := 
GEN_MISC_DIRS__QUOTED := 
C55_DEPS__QUOTED := 
CC_DEPS__QUOTED := 
ASM_UPPER_DEPS__QUOTED := 
SV7A_DEPS__QUOTED := 
S??_DEPS__QUOTED := 
OBJS__QUOTED := 
C67_DEPS__QUOTED := 
K_DEPS__QUOTED := 
S55_DEPS__QUOTED := 
GEN_CMDS__QUOTED := 
GEN_MISC_FILES__QUOTED := 
INO_DEPS__QUOTED := 
C62_DEPS__QUOTED := 
C_DEPS__QUOTED := 
C_UPPER_DEPS__QUOTED := 
C43_DEPS__QUOTED := 
CPP_DEPS__QUOTED := 
BIN_OUTPUTS__QUOTED := 
GEN_FILES__QUOTED := 
C64_DEPS__QUOTED := 
CXX_DEPS__QUOTED := 
CLA_DEPS__QUOTED := 
S_DEPS__QUOTED := 
ASM_DEPS__QUOTED := 
S43_DEPS__QUOTED := 
EXE_OUTPUTS__QUOTED := 
S64_DEPS__QUOTED := 
S62_DEPS__QUOTED := 
PDE_DEPS__QUOTED := 
GEN_OPTS__QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
application/GUI/LVGL_Library/lvgl/env_support/rt-thread \
application/GUI/LVGL_Library/lvgl/env_support/rt-thread/squareline \
application/GUI/LVGL_Library/lvgl/src/core \
application/GUI/LVGL_Library/lvgl/src/draw/arm2d \
application/GUI/LVGL_Library/lvgl/src/draw \
application/GUI/LVGL_Library/lvgl/src/draw/nxp \
application/GUI/LVGL_Library/lvgl/src/draw/nxp/pxp \
application/GUI/LVGL_Library/lvgl/src/draw/nxp/vglite \
application/GUI/LVGL_Library/lvgl/src/draw/sdl \
application/GUI/LVGL_Library/lvgl/src/draw/stm32_dma2d \
application/GUI/LVGL_Library/lvgl/src/draw/sw \
application/GUI/LVGL_Library/lvgl/src/draw/swm341_dma2d \
application/GUI/LVGL_Library/lvgl/src/extra/layouts/flex \
application/GUI/LVGL_Library/lvgl/src/extra/layouts/grid \
application/GUI/LVGL_Library/lvgl/src/extra/libs/bmp \
application/GUI/LVGL_Library/lvgl/src/extra/libs/ffmpeg \
application/GUI/LVGL_Library/lvgl/src/extra/libs/freetype \
application/GUI/LVGL_Library/lvgl/src/extra/libs/fsdrv \
application/GUI/LVGL_Library/lvgl/src/extra/libs/gif \
application/GUI/LVGL_Library/lvgl/src/extra/libs/png \
application/GUI/LVGL_Library/lvgl/src/extra/libs/qrcode \
application/GUI/LVGL_Library/lvgl/src/extra/libs/rlottie \
application/GUI/LVGL_Library/lvgl/src/extra/libs/sjpg \
application/GUI/LVGL_Library/lvgl/src/extra \
application/GUI/LVGL_Library/lvgl/src/extra/others/fragment \
application/GUI/LVGL_Library/lvgl/src/extra/others/gridnav \
application/GUI/LVGL_Library/lvgl/src/extra/others/ime \
application/GUI/LVGL_Library/lvgl/src/extra/others/imgfont \
application/GUI/LVGL_Library/lvgl/src/extra/others/monkey \
application/GUI/LVGL_Library/lvgl/src/extra/others/msg \
application/GUI/LVGL_Library/lvgl/src/extra/others/snapshot \
application/GUI/LVGL_Library/lvgl/src/extra/themes/basic \
application/GUI/LVGL_Library/lvgl/src/extra/themes/default \
application/GUI/LVGL_Library/lvgl/src/extra/themes/mono \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/animimg \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/calendar \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/chart \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/colorwheel \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/imgbtn \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/keyboard \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/led \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/list \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/menu \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/meter \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/msgbox \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/span \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/spinbox \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/spinner \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/tabview \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/tileview \
application/GUI/LVGL_Library/lvgl/src/extra/widgets/win \
application/GUI/LVGL_Library/lvgl/src/font \
application/GUI/LVGL_Library/lvgl/src/hal \
application/GUI/LVGL_Library/lvgl/src/misc \
application/GUI/LVGL_Library/lvgl/src/widgets \
application/GUI \
application \
application/clock \
application/cui \
application/defines \
application/sensor/link_controller \
application/sensor \
software_stack/ti15_4stack/mac \
software_stack/ti15_4stack/mac/low_level \
software_stack/ti15_4stack/mac/mac_settings \
software_stack/ti15_4stack/nv \

